"""empty message

Revision ID: 74377cc56c66
Revises: ed657e16ce20
Create Date: 2018-06-11 13:26:42.704656

"""

# revision identifiers, used by Alembic.
revision = '74377cc56c66'
down_revision = 'ed657e16ce20'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
